### ISSUE TITLE
Make BOLT modular

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/BOLT#1]
BOLT should be modular, so that each functionality can be turned on and off easily.

The modules, which will be loaded at the start, should be defined in the config file. The modules should sit inside a folder `/src/modules/`. Every module should be contained within **one**, inside the modules folder.

**Comment by niklas-heer** [comment]
Awesome work so far @dj95! Would it also be possible to define the commands inside the modules? I think this would make more sense, since it's easier to turn modules off that way.

**Comment by dj95** [comment]
Added with commit e1293c8.
Will be improved later.
