### ISSUE TITLE
the help command should print help for individual commands

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/BOLT#10]
Atm the `/hilfe` command does not print the help text for a specific command. This should be the case considering the increasing numbers of plugins. 
Like this: `/hilfe <command>`

An example:

```
(->) /hilfe meme
(<-) Der Befehl lautet wie folgt:
/meme [meme] ["Oberer Text"] ["Unterer Text"]: Erstellt ein Meme(Alle Memes http://apimeme.com/)


(->) ... user input
(<-) ... output from the bot
```

**Comment by dj95** [comment]
Added with b15ff68
