### ISSUE TITLE
Make the config file into a json file

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/BOLT#3]
This is also necessary for consistency across our projects.
Although admittedly it is open to debate.

**Comment by dj95** [comment]
I would not make the config file with json because one big con is, that you are not able to comment your settings.

**Comment by dj95** [comment]
Maybe we can only take the module activation in json.

**Comment by niklas-heer** [comment]
@dj95 I don't think comments are really needed, because this is a server project with will likely only be of interest to ppl with enough knowledge to understand the config file without comments.
But I can understand if you want to keep your existing config file.
I think having two config files is not a problem, although it is not as clean as having one.

So in this case I would leave the final decision to you.

**Comment by niklas-heer** [comment]
Was fixed with e1293c8
