### ISSUE TITLE
Add full modularity to the modules

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/BOLT#5]
The modules should define their commands themselves instead of defining all commands in `bolt.py`. This is necessary for a clean architecture and the best approach to shut modules off, since the commands will not be loaded. 

Admittedly this architecture is more complex. 
Thoughts on how to solve this are much appreciated!

**Comment by dj95** [comment]
I added new modularity with an extra parser(3a5cae4), so modules will be loaded seperated as defined in the config. Hope it fullfills your expectations.

**Comment by niklas-heer** [comment]
Great work so far! It's definitely better than before, but not quite the full modularity I meant. What I meant is, that everything is done within the module itself, so that you could just make a file in the modules folder and add it to the config and it works.
Much like the old telegram-bot we used.

Maybe you can adapt some concepts to our bot.

See lines 119-124, 144-170 and 256-271. Or maybe other parts, but this are places, which I found quickly, looking over it.
Here is the link: https://github.com/yagop/telegram-bot/blob/master/bot/bot.lua

But your changes are actually a really big step in the right direction and I think this is actually good enough for now, but if it's possible in Python we should do it that way, some day in the future.

So don't be discouraged! You've done a really great job so far!

**Comment by dj95** [comment]
Done with bd9df84
