### ISSUE TITLE
Module request: Memegenerator

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/BOLT#7]
It would be really cool, if you could generate memes like this:

```
/meme <name of the meme> ["<top text>"] [''<bottom text>"]
[ ]  ... optional parameter
< >  ... text placeholder
```

Maybe you could use this API: http://apimeme.com/

**Comment by ghost** [comment]
Okay. It shouldn't be that difficult.

Niklas Heer notifications@github.com schrieb am Do., 16. Juli 2015 10:38:

**Comment by dj95** [comment]
Added with 1ccfb7a
