### ISSUE TITLE
The help list should be displayed in alphabetical order

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/BOLT#9]
Atm the `/hilfe` command doesn't list the commands in alphabetical order. (as shown in the picture below)
This should be changed to sort the list in alphabetical order including the sub-commands, if possible.

![screen](https://cloud.githubusercontent.com/assets/1914063/8894811/1e75ce50-33c4-11e5-9cec-f71e5a0894be.jpg)

**Comment by dj95** [comment]
Added in c900861
